language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - test/gemfiles/5.2.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler --no-document
