language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - test/gemfiles/5.0.gemfile
  - test/gemfiles/5.1.gemfile
  - test/gemfiles/5.2.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem install bundler --no-document
script:
  - bundle exec rake test
  - bundle exec rubocop
